#!/usr/bin/env bash
# Generate the three per-VM node.hcl files from their .example templates.
# Detects this VM's routable IP; override with ADVERTISE_IP=... to be explicit.
#
# Scaling out: run this on each VM with BOOTSTRAP_EXPECT=3, RETRY_JOIN and
# DORIS_CLUSTER set, then `make up` and scripts/install-client.sh.
set -euo pipefail

cd "$(dirname "$0")/.."

ADVERTISE_IP="${ADVERTISE_IP:-$(ip -4 -o route get 1.1.1.1 | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}')}"
NODE_NAME="${NODE_NAME:-$(hostname -s)}"
BOOTSTRAP_EXPECT="${BOOTSTRAP_EXPECT:-1}"
DORIS_CLUSTER="${DORIS_CLUSTER:-a}"
# Space-separated list of the other VMs' IPs, e.g. RETRY_JOIN="10.0.0.1 10.0.0.2 10.0.0.3"
RETRY_JOIN="${RETRY_JOIN:-}"

if [ -z "$ADVERTISE_IP" ]; then
  echo "ERROR: could not detect the routable IP. Set ADVERTISE_IP explicitly." >&2
  exit 1
fi

# Render RETRY_JOIN as an HCL list, and as Nomad server addresses (port 4647).
hcl_list() { local out=""; for a in $1; do out="${out}\"${a}\", "; done; echo "[${out%, }]"; }
hcl_list_port() { local out=""; for a in $1; do out="${out}\"${a}:${2}\", "; done; echo "[${out%, }]"; }

CONSUL_JOIN="$(hcl_list "$RETRY_JOIN")"
NOMAD_JOIN="$(hcl_list "$RETRY_JOIN")"
# A client always needs at least its own VM's server.
CLIENT_SERVERS="$(hcl_list_port "${RETRY_JOIN:-$ADVERTISE_IP}" 4647)"

cat > config/consul/node.hcl <<EOT
# Generated by scripts/init-node.sh on $(date -Iseconds). Edit freely.
node_name        = "${NODE_NAME}"
advertise_addr   = "${ADVERTISE_IP}"
bootstrap_expect = ${BOOTSTRAP_EXPECT}
retry_join       = ${CONSUL_JOIN}
EOT

cat > config/nomad/server/node.hcl <<EOT
# Generated by scripts/init-node.sh on $(date -Iseconds). Edit freely.
name = "${NODE_NAME}"

advertise {
  http = "${ADVERTISE_IP}"
  rpc  = "${ADVERTISE_IP}"
  serf = "${ADVERTISE_IP}"
}

server {
  bootstrap_expect = ${BOOTSTRAP_EXPECT}

  server_join {
    retry_join = ${NOMAD_JOIN}
  }
}
EOT

cat > config/nomad/client/node.hcl <<EOT
# Generated by scripts/init-node.sh on $(date -Iseconds). Edit freely.
name = "${NODE_NAME}"

advertise {
  http = "${ADVERTISE_IP}"
  rpc  = "${ADVERTISE_IP}"
  serf = "${ADVERTISE_IP}"
}

client {
  servers = ${CLIENT_SERVERS}

  meta {
    doris_cluster = "${DORIS_CLUSTER}"
  }
}
EOT

echo "Rendered for node=${NODE_NAME} ip=${ADVERTISE_IP} bootstrap_expect=${BOOTSTRAP_EXPECT} doris_cluster=${DORIS_CLUSTER}"
echo "  config/consul/node.hcl"
echo "  config/nomad/server/node.hcl"
echo "  config/nomad/client/node.hcl"
